### ISSUE TITLE
Change /supporters to /corpmembership or similar

### ISSUE THREAD

**Issue by vanderaj** [OWASP/owasp.github.io#152]
Request from Sherif to make /supporters into /corpmembership

**Comment by hblankenship** [comment]
For what purpose? How does this significantly improve the user experience? Are we wanting a /supporters/ url AND a /corpmembership/ url? Are they different things? How many places refer to /supporters/ instead of /corpmembership/? And should it not really be /corporate-membership/ so we can read it easily? Or maybe we can stick with /supporters/ as most people won't read the url?  We _COULD_ conceivably also put in a redirect from /corpmembership/ to /supporters?  Would that solve an issue that may or may not exist? What about /corporate-membership/? Redirect that too?
