### ISSUE TITLE
Navigation Link Incorrect

### ISSUE THREAD

**Issue by SavPhill** [OWASP/owasp.github.io#196]
Navigation: The tab titled Caribbean in the navigation menu under the main Chapter tab is incorrectly linked to the id #TheCaribbean. This navigates to the page correctly, but not to the correct section, as the id is #Caribbean.

**Comment by Shu12388y** [comment]
Hi shubham here, can you assign this issue to me. I want to work on this issue

**Comment by cywf** [comment]
I adjusted the our owasp san juan [repo](https://github.com/owasp/www-chapter-san-juan) because it was incorrectly changed by someone (outside of our chapter btw), we (currently) are the only chapter formed in the Caribbean Islands, a fact we are quite excited to be able to potentially change / add too. So naturally, when I saw this commit reverting our chapter **from** the [Caribbean page](https://owasp.org/chapters/#Caribbean) **to** the [Central America](https://owasp.org/chapters/#CentralAmerica) section with a self approved commit from someone (again this person is **not** one of the leaders, **or** a member of the chapter, nor left any informative details as to why this change was necessary)

I'll open a separate Issue on this, bc it needs to reflect on the main page, but thought since your issue was open since before all of this happened, I thought to be curtious and throw an update, since it related

**Comment by CHARANCHARY** [comment]
sir please assign me to solve this issue

**Comment by tonyvg2013** [comment]
not assigned I assume.

**Comment by cywf** [comment]
apologizes for the delay, verified that correction has been made, so I will close this issue tyvm

**Comment by SavPhill** [comment]
> apologizes for the delay @CHARANCHARY , I've verified that correction has been made, however I do not have the perms to assign this issue to anyone, due to @SavPhill being the one who opened the original issue. This issue seems to be resolved to me, so if you (@SavPhill) wanna close it go for it! Appreciate you all! 

The issue is still outstanding. If you follow the menu link in Chapters > Caribbean. The ID in the URL and spelling of the word Caribbean is still incorrect:

This is the URL currently:

https://owasp.org/chapters/#TheCarribean

This is what the URL should be:

https://owasp.org/chapters/#Caribbean
