### ISSUE TITLE
excess div tag on membership page

### ISSUE THREAD

**Issue by zerexei** [OWASP/owasp.github.io#207]
url: https://owasp.org/membership/

![image](https://user-images.githubusercontent.com/69749146/212785080-2f652020-31c5-4d75-9c7a-a8f2974a8207.png)

**Comment by ginisha02** [comment]
so in this we have to remove this tag?

**Comment by SpindleSec** [comment]
The `<div>` elements aren't actually unbalanced, but they're being rendered as text for some reason. I've just submitted [a PR](https://github.com/OWASP/owasp.github.io/pull/208) that removes a bunch of whitespace which I _think_ will fix it. I'll confess that I haven't read up on which markdown engine it's using, or the exact behaviour, but the GitHub preview at least renders the block as text, rather than as `<pre>`. Might need a maintainer with a bit more knowledge to test it.

**Comment by hblankenship** [comment]
was actually due to a missing end li tag in another file. Thanks.
