### ISSUE TITLE
Get Membership Status hangs

### ISSUE THREAD

**Issue by rewtd** [OWASP/owasp.github.io#58]
On attempting to verify membership status the page partially loads with three errors and two warnings.
<img width="354" alt="get_membership_status_hangs" src="https://user-images.githubusercontent.com/6101839/73591394-07aa7580-44e6-11ea-88b0-a6d4745e7b03.PNG">

Error 1
X-Frame-Options may only ?token=c2MAAoge0Lq7XT8mhdL8EogMFmlTHS9GBhHysgaIqKNk7fT92cVHrX890iancl2oykth1ZilT6MW8olgfewbznnDZMQ6efa5W30n7RbCzFzl%2FCdXNbaHveSJ4cFvgdbG%2Bw%3D%3D:19 X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.

Warning 1
A cookie associated with a cross-site resource at https://m.stripe.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Warning 2
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Utils.getStringFromFile @ yaml.min.js:1

Error 2
Failed to load resource: billingmanagement:1 the server responded with a status of 500 (Internal Server Error)

Error 3
spread.js:25 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (spread.js:25)
    at e.exports (spread.js:25)
    at XMLHttpRequest.l.onreadystatechange (spread.js:25)
e.exports @ spread.js:25
e.exports @ spread.js:25
l.onreadystatechange @ spread.js:25

**Comment by ninjasimon** [comment]
Can you please try loading that URL again?  I think I've fixed the issue preventing your membership data from loading correctly.

Regarding Error 1 - I believe this is because we are setting X-Frame-Options as a meta tag rather than a header.  I'll let someone working on the markup of the site address that.

Regarding Warning 2 - This is due to Stripe's client library, which we must include in order to process payments.

Neither of the above console entries were actually causing the problem preventing your membership data from loading - that was due to the 500 error which should be resolved now.

**Comment by rewtd** [comment]
Thank you @ninjasimon it was successful now.
