### ISSUE TITLE
Typo on OWASP NZ day 2020

### ISSUE THREAD

**Issue by dark-binary** [OWASP/owasp.github.io#60]
https://wiki.owasp.org/index.php/OWASP_New_Zealand_Day_2020#tab=Conference_-_21_February

In the above-mentioned link, the conference schedule is drafted for OWASP NZ day 2020. It is to be held on 21st February 2020 but it looks like there has been a typo mentioning it as 2019.

<img width="1440" alt="Screenshot 2020-02-03 at 5 48 34 PM" src="https://user-images.githubusercontent.com/51049418/73626394-9ae1d780-46ad-11ea-9ecf-7e1ef29e4256.png">

**Comment by sheepbaron** [comment]
More typos:

Resource: https://owasp.org/www-project-cheat-sheets/cheatsheets/Input_Validation_Cheat_Sheet.html

1. The following sentence does not quite make sense; it appears there are some words missing in the following sentence: "It is a common mistake black list validation in order to try to detect possibly dangerous characters and patterns like the apostrophe.."

2. "Defines a minimum and maximum length for the data" should read "Define a minimum and maximum length for the data"

3. "Validating an U.S. Zip Code" should read "Validating a U.S. Zip Code"

4. "although there are a number of publicly documents regex." should read something like "although there are a number of public documents on this topic.".

**Comment by aayush420** [comment]
Addressed in Pull request 15

**Comment by hblankenship** [comment]
As per above. Typos on particular repos should be against those repositories and not against the general owasp.org (this) repo.
